name: Generate Snake

on:
  schedule: # run automatically every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # run manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: YOUR_USERNAME
          outputs: dist/snake.svg

      - name: Push Snake Game to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
